888[p44444444444446
title: "temperature boxplots"
author: "Katie O'Brien-Clayton"
date: "2023-06-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##R Markdown for temperature boxplots


```{r}
library(ggplot2)

library(dplyr) #You don't actually need this package for the code below but dplyr is very handy most of the time

library(readxl)

 

test <- read_excel("C:\\R\\data\\Temperature2023_copy.xlsx")

##Reorder
## 
cruiseOrder <- factor(test$Cruise, levels = c("WQJAN", "WQFEB", "WQMAR", "WQAPR", "WQMAY", "WQJUN", "HYJUN", "WQJUL", "HYJUL", "WQAUG", "HYAUG", "WQSEP", "HYSEP", "WQOCT", "WQNOV", "WQDEC"))

ggplot(data = test, aes(x = cruiseOrder, y = AvgTemp))+

  geom_boxplot(aes(fill = Depth))+
theme_classic()+
##Creates a boxplot and assigns a fill color
  
  
   geom_point(data = subset(test, test$Year == "2023"), aes(x = Cruise,
                                                               y = AvgTemp),
            colour = "seashell3", shape = 17)+

  labs(x= "Cruise", y="Average Temperature (deg C)")+
  
  
   ggtitle("Average Long Island Sound Water Temperatures 2013-2023")+ #Assigns a title and subtitle to the graphic

  ##theme_bw() #Various default themes in R, I use this often since it puts up a white background.

     theme(legend.position = "right", #Further customization of theme= none, left, right, top, bottom

        plot.title = element_text(size = 15), # adjust size of plot title

        axis.title = element_text(size = 15), # adjust size of axis title

        strip.background = element_rect(colour="black",
                                        fill="white"),
        
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) #adjust axis text
  
  

#Saves graphic in a specific location and in a specific format (.png) and size
ggsave(paste0("C:\\R\\plots\\AvgTempData_2013-2023.png"), height = 7.2, width = 10)
```
```

